### ISSUE TITLE
Option to have dragging the main graph "translate" instead of "select + zoom"?

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#1]
Similar behaviour to google finance's

https://www.google.com/finance?q=INDEXDJX%3A.DJI%2CINDEXSP%3A.INX%2CINDEXNASDAQ%3A.IXIC&ei=75lZWMH2F4qkjAG29LqoDQ

**Comment by alex-wilmer** [comment]
This feature is not well documented at all but try zooming the dragging the 'map' by clicking on the little white box with the arrow

![image](https://cloud.githubusercontent.com/assets/2880089/21368555/157886b6-c6d1-11e6-9a80-5b1e6781c874.png)

Is this generally speaking what you're thinking?

**Comment by cheapsteak** [comment]
Yup!

**Comment by alex-wilmer** [comment]
Should I close this? I'm open to ideas for ways on improving this feature, kinda snuck it in there.

**Comment by cheapsteak** [comment]
Sounds good  :)
