### ISSUE TITLE
Callbacks for handlers not receiving original event

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#18]
Handlers for `onMutationMouseover`, `onMutationMouseout` etc currently only return the data

e.g. in [mutations.js](https://github.com/oncojs/lolliplot/blob/master/modules/node_modules/%40oncojs/lolliplot/mutations.js#L72)
```js
    .on(`mouseover`, d => {
      if (!store.getState().animating) {
        if (onMutationMouseover) {
          onMutationMouseover(d)
```

Please pass along the original event as well for positioning purposes

Can't use a custom tooltip otherwise

(Since different versions of d3 are used, we can't call d3.event inside our handler)

**Comment by alex-wilmer** [comment]
That's a good idea. I have a suggestion about tooltips though in case this interests you. I've been using a "global" tooltip in GDC which is always rendered and follows the mouse around. it's always perfectly positioned (kinda like when you mouseover the bar charts in dcc) then other events just toggle its visibility. I quite fond of its simplicity

**Comment by cheapsteak** [comment]
We had issues with global tooltips where when you call `element.requestFullscreen()`, the global tooltip would not show up since it's outside of the `element`. Do you guys have a solution for that?

**Comment by alex-wilmer** [comment]
Have not looked into it, but I will now!

**Comment by cheapsteak** [comment]
Oh, my mistake then, I didn't realize they interoperated like that  
How do you feel about passing back the event though? I think it might be a cleaner api to not have to require the handler to require d3 to access an event

**Comment by alex-wilmer** [comment]
passed in as second arg, cool?

**Comment by cheapsteak** [comment]
awesome, thanks!
