### ISSUE TITLE
Plot not taking up full width

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#20]
I'm passing in the width explicitly, not sure what's going on here
![image](https://cloud.githubusercontent.com/assets/743976/21431967/666cd61e-c81e-11e6-9ede-62023ab76a88.png)

**Comment by cheapsteak** [comment]
Oh, I think this might be due to the error in #14 resulting in the stats panel not being drawn
Would prefer to have the plot just be the plot, and have the stats panel be opt-in
Ideally have the stats panel be a separate piece, and have the plot expose API to allow for custom stats panels

**Comment by alex-wilmer** [comment]
Yeah a custom stats panel would be cool. While its broken though you can run the top level function with ` hideStats: true`

**Comment by cheapsteak** [comment]
Ah yup I should have read that
Thanks for the tip!
