### ISSUE TITLE
Expose items in viewport as an observable or a callback?

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#21]
The items in view on the viewport seems like it might make sense to be an observable that other things can subscribe to

Proposed api
```js
const plot = lolliplot({/*...*/})
plot.viewport.subscribe(({mutations, start, end}) => {
  updateStats({mutations})
})
```

Although rxjs does maybe seem a bit heavy to bring in just for one function, maybe it could just be a callback
```js
loliplot({
  //...
  onViewportChange: ({mutations, start, end}) => /**/
})
```

edit:
another option if there are other things besides viewport that may change (can't think of what though):
```js
loliplot({
  //...
  onUpdate: ({viewport: {mutations, start, end}, otherThings}) => /**/
})
```

**Comment by alex-wilmer** [comment]
This is a great idea. I thought about it before, but definitely convinced

**Comment by alex-wilmer** [comment]
I'm exporting the store creation function together with the main library now

here's an example of me using `store.subscribe` to set some values outside of the chart once the user interacts:


```
import ProteinLolliplot, { setupStore } from '@oncojs/lolliplot'

let zoomMinInput = document.querySelector(`#zoom-min`)
let zoomMaxInput = document.querySelector(`#zoom-max`)

zoomMinInput.value = 0
zoomMaxInput.value = domainWidth

store.subscribe(() => {
  let { targetMin, targetMax } = store.getState()
  zoomMinInput.value = targetMin
  zoomMaxInput.value = targetMax
})
```

**Comment by cheapsteak** [comment]
Does the created store get passed into `ProteinLolliplot` as part of the constructor options?

**Comment by alex-wilmer** [comment]
yea I made it optional. if you don't provide the store yourself it will make a default one

```
store = setupStore({ domainWidth }),`
```

**Comment by cheapsteak** [comment]
Can I subscribe to the one that gets created by default instead of creating my own?

**Comment by alex-wilmer** [comment]
oh for sure, I just added `store` to part of the return. is that adequate?

**Comment by cheapsteak** [comment]
Yup that's awesome :D
