### ISSUE TITLE
Do not call updateStats if hideStats is true

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#29]
Making a separate ticket in case it gets buried in the performance thread :)
![image](https://cloud.githubusercontent.com/assets/743976/21699120/3a11fbda-d368-11e6-9b19-368662dedd8d.png)

Even with animations turned off, dragging the selection thing around is quite choppy mostly due to calls in updateStats

Would be great if we could bypass that if stats are hidden

**Comment by alex-wilmer** [comment]
https://github.com/oncojs/lolliplot/commit/8407fcc4fdca93f20fe63e87add23bea6ac9d06e
