### ISSUE TITLE
Resize chart when the container resizes

### ISSUE THREAD

**Issue by alex-wilmer** [oncojs/lolliplot#3]

**Comment by alex-wilmer** [comment]
does it make sense to handle this outside of the chart? I'm doing this in the example code now

```
window.addEventListener(`resize`, () => {
  remove()
  proteinLolliplot = ProteinLolliplot(opts)
  draw = proteinLolliplot.draw
  remove = proteinLolliplot.remove
})
```

**Comment by alex-wilmer** [comment]
could potentially add a flag, which would do that internally, and send a callback once finished

**Comment by alex-wilmer** [comment]
cc @cheapsteak

**Comment by cheapsteak** [comment]
Having to destroy and recreate the chart on resize might seem a bit unintuitive   
I would prefer to have a `chart.resize({width, height})`, but could perhaps leave the event listening to the user (in case they want to debounce or something)
What do you think?

**Comment by alex-wilmer** [comment]
yea I realized that was a bad idea. will create that function and keep tabs on it here https://github.com/oncojs/lolliplot/issues/19
