### ISSUE TITLE
Odd rendering offset

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#31]
Things seem to be shifted right more than they should

![image](https://cloud.githubusercontent.com/assets/743976/21700603/3cc05f96-d36f-11e6-8cbd-9cf023e93aca.png)
![image](https://cloud.githubusercontent.com/assets/743976/21700694/bc430d04-d36f-11e6-8eab-ae7e16819383.png)

Visible here:
https://dev.dcc.icgc.org:8916/genes/ENSG00000183117

**Comment by alex-wilmer** [comment]
ooo I think I fixed this already. what version are you on?

**Comment by cheapsteak** [comment]
Oh nice, I'm on 0.5.5, will retry with keyway tomorrow :)
