### ISSUE TITLE
Data format / sample data?

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#5]
Could you provide a sample data file to see what format the data input should be?

Couldn't dig it out of http://45.55.239.144:8001/static/bundle.js

**Comment by shanewilson** [comment]
maybe this? 
https://github.com/oncojs/lolliplot/blob/master/modules/node_modules/%40oncojs/lolliplot/data.js

**Comment by cheapsteak** [comment]
Yup! I'd completely ignored the node_modules folder, my bad
