### ISSUE TITLE
Remove dependency on redux

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#6]
Why does this need redux?
![image](https://cloud.githubusercontent.com/assets/743976/21398348/e0382282-c75b-11e6-85ab-8bac99b91183.png)

**Comment by alex-wilmer** [comment]
To manage state? Is that a problem?

**Comment by cheapsteak** [comment]
Ah, apologies, I thought maybe you were testing with react and forgot to take it out, my mistake
