### ISSUE TITLE
Make d3@4 a direct dependency until this library supports d3@3?

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#7]
DCC Portal is still on d3 v3, resulting in error of 'd3.scaleOrdinal is not a function'
I can't think of another way to solve this other than to make d3 a direct dependency instead of a peer dependency

**Comment by alex-wilmer** [comment]
https://github.com/oncojs/lolliplot/commit/17558ea22351d3e5563a3e6a7763d6cf69e44b4b

Take a look at the package.json  https://github.com/oncojs/lolliplot/blob/master/package.json#L50
I think these are the correct dependencies, and if you don't provide the d3 library in the init function it will throw, but will work if you pass it a v3 or a v4 version of the library.

This way I'm able to remove `import * as d3` everyone from the actual library code.

**Comment by alex-wilmer** [comment]
actually, I'm moving d3 to `devDependencies` not peer, that way its the users responsibility to ensure they have d3 loaded somehow, not necessarily through npm
