### ISSUE TITLE
Scope selectors to container element

### ISSUE THREAD

**Issue by cheapsteak** [oncojs/lolliplot#8]
Selections within the library should be scoped to the container element

e.g.
zoom.js 

```js
  let minimap = document.querySelector(`.minimap`)
  let chart = document.querySelector(`.chart`)
  let chartZoomArea = document.querySelector(`.chart-zoom-area`)
  let slideTarget = document.querySelector(`.minimap-slide-target`)
```
https://github.com/oncojs/lolliplot/blob/master/modules/node_modules/%40oncojs/lolliplot/zoom.js#L54-L57

mutations.js

```js
var mutationChartLines = d3.select('.chart') //...
```

Cases to  consider:
- multiple instances of lolliplot on a single page
- common selectors being used by other things on the page (global selectors like `document.querySelector` are dangerous)
- chart being initialized in a document fragment (document.querySelector would not find it)

**Comment by alex-wilmer** [comment]
WIP here https://github.com/oncojs/lolliplot/tree/scoping

**Comment by alex-wilmer** [comment]
https://github.com/oncojs/lolliplot/commit/954f2becc365d3b1795116bba0b03df73393290e
